# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b4919c7ea80e92e1310263e70c58a7248163bf88426a5f8d7ef9a92ca89c3acc6ae0182b438b3d25889aec028442d242c6887729a1de0cdb5194ee2266c4ffc

test:
  secret_key_base: 00269a942915b8db035e13eeb35f41ffe43569bbc6d592c381716b1e8853300dd385ba7487a277a38f6553dcdacb83ca16fb718945c3c50fd2f35a95a201ba5e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
